import type { Metadata } from "next";

import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={` antialiased`}
      >
        <Sidebar />
       <div className=" "> {children}</div>
      </body>
    </html>
  );
}
